image: Visual Studio 2022

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk17
    - JAVA_HOME: C:\Program Files\Java\jdk21
    - JAVA_HOME: C:\Program Files\Java\jdk25

install:
  - set VERSION=9.2.1
  - set GRADLE_DIR=C:\gradle
  - set DOWNLOAD_URL=https://services.gradle.org/distributions/gradle-%VERSION%-bin.zip
  - ps: wget $env:DOWNLOAD_URL -O gradle-bin.zip
  - mkdir %GRADLE_DIR%
  - 7z x gradle-bin.zip -o%GRADLE_DIR%
  - set PATH=%GRADLE_DIR%\gradle-%VERSION%\bin;%PATH%
  - gradle -v

build_script:
  - gradle assemble --no-daemon

test_script:
  - gradle check --no-daemon

cache:
  - C:\Users\appveyor\.gradle
